BD_KEYWORDS = [
    "BTV","ATN","Channel i","Jamuna","Somoy","Ekattor","NTV","Bangla","Boishakhi","Desh","Gazi","DBC","MyTV","SA TV","RTV","Maasranga","Shomoy","Independent TV","News24","Channel 24","Mohona","Bijoy","Bangladesh Television","Bangladesh Parliament Television","BanglaVision","Asian TV","Duronto TV","Ananda TV","Deepto TV","Nagorik TV","Bangla TV","Global TV","Channel S","Green TV","Ruposhi Bangla","Movie Bangla","Music Bangla","Bangla Plus","Channel 9"
              ]
INDIA_KEYWORDS = [
    "Star","Zee","Sony","Colors","Republic","Sun","DD","Aaj Tak","India TV","NDTV","TV9","ABP","Asianet","Maa","&TV","Dangal","Big Magic","Sansad","News18","Times Now","News Nation","CNBC","ET Now","Sports18","Eurosport","B4U","UTV","Movies Now","MNX","Romedy Now","9XM","9X","Zing","MTV","VH1","Music India","Cartoon Network","Pogo","Discovery","Nick","Disney","Hungama","History","Animal Planet","National Geographic","Nat Geo","Travel XP","Food Food","Aastha","Sanskar","Sadhna","Vedic","KTV","Kalaignar","Jaya","Raj","Vijay","Adithya","Gemini","ETV","Surya","Flowers","Manorama","Mathrubhumi","Udaya","Public","Suvarna","Power","Majha","Bangla","PTC","Chardikla","Tarang","Kanak","OTV","Kalinga","Prameya","TV5","V6","N TV","10TV","Sakshi","ABN","Studio N"
    ]

CARTOON_KEYWORDS = [
    "Cartoon Network","Nick","Nickelodeon","Disney","Pogo","Hungama","BabyTV","Toon","CBeebies","Baby","Kids","Boomerang","Cartoonito","Toonami","Tooncast","Disney Channel","Disney Junior","Disney XD","Nick Jr","Nicktoons","TeenNick","NickMusic","PBS Kids","Universal Kids","CBBC","Pop","Pop Max","Tiny Pop","YTV","Teletoon","Treehouse TV","Family Channel","Family Jr","Family CHRGD","KIKA","Super RTL","TOGGO","RTL Super","Boing","Canal Panda","Clan TVE","Rai Yoyo","Rai Gulp","JimJam","BabyFirst","ZooMoo","Da Vinci Kids","Knowledge Kids","Moonbug Kids","Spacetoon","Majid Kids","Ajyal TV","Alwan TV","CN Arabic","MBC3","Jeem TV","Baraem","Qatar Kids","Sharjah TV Kids","Al Rayyan Kids","Super Hungama","Sony YAY","Discovery Kids","Marvel HQ","Animax","Aniplus","Kids Station","NHK E Tele","NHK Kids","Tooniverse","Champ TV","Anione","Anibox","Kids TV Japan","TV Tokyo Kids","BS11 Kids","DreamWorks Channel","DreamWorks Asia","DreamWorks Kids","DreamWorks Animation","Kids Central","Okto","ABC Kids","ABC ME","RiC TV","Fix & Foxi","Panda Kids","Frisbee","DeAKids","DeA Junior","Canal J","Gulli","Gulli Max","TiJi","Piwi+","Gloob","Gloobinho","TV Rá-Tim-Bum","Mindset Kids","Akili Kids","eToonz","Smile TV","Smile of a Child","Yippee TV","Yippee Kids","Sonlife Kids","God TV Kids","CoComelon TV","CoComelon Kids","Ryan & Friends","Ryan and Friends","Little Angel TV","Super Simple TV","KidsFlix","Kidoodle TV","Da Vinci Learning Kids","Curiosity Kids","Curiosity Stream Kids","Toon Goggles","BatteryPop","Anime Network","Anime Channel","KidsCo","Hop","Hop TV","Hop Channel","Panda Futura","Baby TV Turkey","Minika Çocuk","Minika GO","TRT Çocuk","TRT Kids","Yumurcak TV","Ketnet","Karusel","Multimania","Polsat JimJam","Teletoon+","MiniMini+","Hop Israel","Junior TV","Logi TV"
                   ]
NEWS_KEYWORDS = [
    "News", "Samachar", "Khobor", "BBC", "CNN", "Al Jazeera",
    "CNBC", "Bloomberg", "Sky News", "France 24", "DW", "Euronews",
]

SPORTS_KEYWORDS = [
    "Sport","ESPN","Star Sports","Sony Six","Ten Sports","Willow","DSport","Cricket","Football","FIFA","Sky Sports","BT Sport","Sony LIV Sports","FOX Sports","FS1","FS2","beIN Sports","DAZN","Eurosport","TNT Sports","Premier Sports","SuperSport","Sports18","Sony Sports Ten","FanCode","JioSports","TSports","Toffee Sports","GTV Sports","RMC Sport","Canal+ Sport","Canal+ Foot","Canal+ Rugby","Viaplay Sports","Viaplay Xtra","Sport TV","Premier League TV","LFCTV","MU TV","Manchester United TV","City+","Real Madrid TV","Barca TV","Barca One","Inter TV","AC Milan TV","Juventus TV","Eleven Sports","Mola TV Sport","Astro SuperSport","Astro Arena","Astro Cricket","True Sport","True Premier Football","SPOTV","J Sports","KBSN Sports","SBS Sports","MBC Sports+","Coupang Play Sports","CCTV Sports","CCTV5","CCTV5+","CCTV Olympic","iQIYI Sports","Tencent Sports","Dubai Sports","Dubai Racing","Abu Dhabi Sports","Oman Sports","Kuwait Sports","Saudi Sports","SSC Sports","Qatar Sports","Al Kass Sports","Ziggo Sport","Polsat Sport","TVP Sport","Nova Sport","Sport Klub","Arena Sport","RTS Sport","Movistar Deportes","Movistar LaLiga","Movistar Liga de Campeones","TUDN","Univision Deportes","Telemundo Deportes","Universo Deportes","Gol TV","GOL PLAY","TyC Sports","BandSports","Premiere Futebol","Sportv","Claro Sports","Win Sports","Caracol Sports","RCN Deportes","Azteca Deportes","Canal 5 Deportes","PTV Sports","A Sports","Geo Super","Tapmad Sports","Prime Sports","Sports TV Cricket","Fox Cricket","Channel 7 Sport","Nine Sport","ATP Tennis TV","WTA TV","Tennis Channel","Golf Channel","Formula 1 TV","F1 TV","Motorsport TV","Motorvision TV","Auto Motor Sport","Speedvision","NBA TV","NFL Network","NFL RedZone","MLB Network","NHL Network","Fight Network","UFC Fight Pass","UFC TV","WWE Network","WWE Channel","AEW Plus","BoxNation","DAZN Boxing","Premier Boxing Champions","Extreme Sports","Fuel TV","Red Bull TV","Red Bull Racing","Surf Channel","World Surf League TV","Fishing TV","Horse TV","Racing TV","At The Races","Equidia","Chess TV","PokerGO","Poker TV","Motors TV","Bike Channel","Bike TV","Outdoor Channel","Hunting Channel","Fishing Channel","Adventure Sports TV","Adventure Sports Network","World Chase Tag TV","Olympic Channel","World Athletics Channel","FIBA TV","Volleyball World TV","World Rugby TV","Handball TV","Formula E TV","FIA WEC TV","TSN","Sportsnet","RDS Sport","NBC Sports","YES Network","MSG Network","NESN","Altitude Sports","Marquee Sports Network","SEC Network","ACC Network","Big Ten Network","Pac-12 Network","FanDuel Sports Network","Golazo Network","Kayo Sports","Stan Sport","Optus Sport","Sky Sport NZ","Zee Sports","DD Sports","Sport1","Sportdigital","RTÉ Sport","TG4 Sport","NOS Sport","V Sport","Match TV","Match Premier","Okko Sport","Setanta Sports","VTV Cabal Sport","VTV Sports","DirecTV Sports","D Sports","Caribbean Sports Network","SportsMax","Flow Sports"
                  ]
MOVIES_KEYWORDS = [
    "Movies","Cinema","Film","Zee Cinema","Star Gold","Sony Max","B4U","Action","Thriller","Romedy","&Pictures","Star Movies","Zee Bollywood","Zee Action","Zee Classic","Zee Anmol Cinema","Sony Wah","Colors Cineplex","Movies Now","MNX","Romedy Now","UTV Movies","UTV Action","Zee Studio","HBO","Cinemax","AMC","FXM","FXX","Showtime","Starz","Encore","Paramount Network","Comedy Central","MTV Movies","Film4","Great! Movies","Talking Pictures TV","Canal+ Cinema","Canal+ Family","Canal+ Action","Canal+ Premier","Sky Cinema","Netflix Movies","Prime Movies","Rakuten TV Movies","Fox Movies","Fox Action Movies","Fox Family Movies","True Film","True Movie","Cinema One","Cinema World","Cinema Asia","Movie Channel","The Movie Channel","Zee Cinemalu","Zee Thirai","Zee Flix","Zee Theatre","Manoranjan Movies","Manoranjan Grand","Enterr10 Movies","Enterr10 Bangla","Rishtey Cineplex","Goldmines","Dhinchaak","Movie Plus","Wow Cinema","Sun TV Movies","KTV","Sun Life","Kalaignar Movies","Raj Digital Plus","Raj Movies","Jaya Max","Adithya TV","Gemini Movies","Udaya Movies","Surya Movies","Asianet Movies","Zee Keralam Movies","Zee Marathi Movies","Zee Bangla Cinema","Zee Punjabi Cinema","Movies OK","Celestial Movies","Celestial Classic Movies","Thrill","Hits Movies","Hits","BeTV Movies","DreamWorks","DreamWorks Animation","OSN Movies","MBC Bollywood","MBC2","MBC Max","MBC Action","Rotana Cinema","Rotana Classic","Rotana Drama","Dubai One","Abu Dhabi Movies","Al Aan Movies","TNT","TBS","TCM","Syfy","Universal TV","Universal Channel","Universal Movies","Hallmark Movies & Mysteries","Hallmark Channel","Hallmark Drama","Lifetime Movies","Lifetime Movie Network","Freeform","ABC Family","Bounce TV","Bounce XL","ION Television","ION Mystery","ION Plus","TruTV","Vice TV","Pop TV","WE tv","Showcase","Showcase Action","Showcase Classics","OCS Max","OCS City","OCS Choc","RTL Crime","RTL Passion","RTL Living","ProSieben FUN","Kabel Eins Classics","Sat.1 Emotions","Tele5","Kinowelt TV","Warner TV Film","Warner TV Comedy","Space","Studio Universal","Universal Cinema","Golden Premier","Golden Edge","HBO Plus","Moviecity","Moviecity Action","Moviecity Family","Cinecanal","The Film Zone","NHK BS Premium","NHK BS Cinema","WOWOW Cinema","WOWOW Prime","WOWOW Live","Star Chinese Movies","Phoenix Movies","Phoenix Movie Channel","China Movie Channel","CCTV Movie","CCTV6","TVB Movies","TVB Jade Movies","TVB Pearl","ViuTVsix","One TV","One Movies","J Movie","K Movie Channel","KMOVIE","Mono29","Mono Max","Channel Film","Zee Film","ETV Cinema","Star Utsav Movies","Movies Central","Star Chinese Movies Legend","OSN Movies First","Rotana Aflam","Al Kass Movies","Saudi Cinema","Dubai Zaman","AMC Middle East","FOX Movies Middle East","FilmBox","FilmBox Plus","FilmBox Action","FilmBox Family","FilmBox Arthouse","Bollywood HD","Bollywood Classic","Bollywood Hits","Cinema TV","Action Max","Drama Max","Family Max"
                  ]
MUSIC_KEYWORDS = [
    "Music","MTV","VH1","Channel V","Zing","9X Jalwa","Hits","Beats","Radio","4Music","The Box","Kerrang!","Kiss TV","Vevo","Trace","iConcerts","Qello Concerts","Stingray","Music Choice","NOW","Clubland TV","Chart Show TV","Heart TV","Magic TV","Magic Soul","Kiss","Box Hits","Channel U","Channel AKA","Mezzo","Classica","NickMusic","Music India","9XM","Zoom","ETC Bollywood","B4U Music","Zee Music","Zee ETC","Showbox","Bindass","DD National Music","Sun Music","Sun News Music","KTV Music","Isaiaruvi","Jaya Max","Raj Musix","Gemini Music","ETV Plus Music","ETV Telugu Music","Udaya Music","Surya Music","Asianet Music","Zee Bangla Music","PTC Punjabi Music","PTC Chakde","MH1","Channel Punjabi","Punjabi Hits","Colors Bangla Music","Anjan TV","Star Vijay Music","Music Box","Yin Yue Tai","QQ Music TV","JOOX TV","Arirang","K-Pop TV","Mnet","1theK","Music On! TV","Space Shower TV","Arabic Music","Rotana Music","Rotana Clips","Nogoum FM TV","Mazzika","Melody Hits","Melody Aflam Music","Afro Music","Channel O","Sound City","RFM TV","NRJ Hits","Clubbing TV","Deluxe Music","DMAX Music","Folx TV","Viva","Hit TV","Hit Radio TV","Schlager Deluxe","Channel One Russia Music","RU.TV","Muz TV","Europa Plus TV","Bridge TV","Latino Music","HTV","Telehit","BandaMax","Ritmoson","Canal Fiesta","Music Top","Afrobeats TV","Gospel Music Channel","Hope Channel Music","Country Music TV","CMT","Country Network","Classic Arts Showcase","Concert Channel","Live Concert Channel","Live Music TV","Karaoke TV","Karaoke Channel","Dance Nation TV","Retro Music TV","Vintage TV"
    ]

FIFA_KEYWORDS = [
    "T Sports","BBC ONE","BBC TWO","ITV","ITV1","FOX","FS1","FOX Sports","Telemundo","FIFA World Cup","TSN 1","FOX FHD","WC TV","CTV","CazeTV","beIN Max AR","Fussball","Tipik","D Sports","M6","BBC 1","ORF","VRT","TUDN","TVE LA","TVP","Cignal","TSN 2","FS1","Go Live","SporTV","World Cup","FIFA 2026","WC 2026","Football World Cup","Soccer World Cup","Unite 8 Sports 1 HD","Unite 8 Sports 2 HD","Somoy","PTV 4K","S Football","TVP Sports"
                ]


# Category display names & priority order
CATEGORY_ORDER = ["bd", "india", "cartoon", "news", "sports", "movies", "music", "other", "FIFA"]

CATEGORY_LABELS = {
    "bd":      "Bangladesh",
    "india":   "India",
    "cartoon": "Kids & Cartoon",
    "news":    "News",
    "sports":  "Sports",
    "movies":  "Movies",
    "music":   "Music",
    "other":   "Other",
  "FIFA":    "FIFA WORLDCUP 2026",
}

# ── Performance tuning ────────────────────────────────────────────────────────
MAX_WORKERS    = 200    # parallel threads for downloading & checking URLs
SOURCE_TIMEOUT = 10    # seconds to wait when fetching a source playlist
CHECK_TIMEOUT  = 5     # seconds per URL reachability check

# True  → skip per-URL check (fast, finishes in minutes, keeps dead links)
# False → HTTP HEAD/GET check each URL (filters dead links, recommended)
SKIP_URL_CHECK = False

# How many retries on connection error before marking a URL dead
CHECK_RETRIES = 1
