FIFA_KEYWORDS = ["T Sports","TSports","BBC","BBC ONE","BBC TWO","ITV","ITV1","FOX","FS1","FOX Sports","Telemundo","Universo","TUDN","Univision","TSN","CTV","RDS","SBS","TVNZ","beIN","beIN Sports","beIN MAX","beIN Sports MAX","M6","ARD","ZDF","MagentaTV","RTVE","La 1","Teledeporte","RAI","Rai 1","Rai Sport","VRT","RTBF","Sporza","Tipik","NOS","ORF","ServusTV","SRF","RTS","RSI","RTP","Globo","SporTV","CazéTV","CazeTV","SBT","N Sports","Televisa","TV Azteca","Telefe","TV Publica","TyC Sports","Caracol","RCN","Win Sports","Chilevision","America Television","SuperSport","New World TV","TRT","Match TV","CCTV5","CCTV Sports","Migu","NHK","Fuji TV","Nippon TV","DAZN","JTBC","Sony Sports","Sony Ten","PTV Sports","Arena Sport","Sport TV","Eleven Sports","Canal+","Eurosport","Premier Sports","D SPORTS","Cignal","Shomoy","BTV","Toffee","Bioscope","Sky Sports","Sky Sport","ESPN","ESPN Deportes","Gol Mundial","FUSSBALL","Sportklub","TVP Sport","Polsat Sport","Sportdigital","Viaplay","V Sport","TV2 Sport","NRK","SVT","TV4","Yle","MTV3"
               "FanCode", "FANCODE", "Sky F1", "Sky F1 DE", "Sky Sport FHD", "Sky Sport HD", "Tipik", "FIFA World Cup",
    "World Cup",
    "FIFA 2026",
    "WC 2026",
    "Football World Cup",
    "Soccer World Cup", "Unite 8 Sports 1 HD",
    "Unite 8 Sports 2 HD",
    "Somoy",
    "PTV 4K",
    "S Football",
    "TVP Sports",
]

BD_KEYWORDS = [
    "BTV", "ATN", "Channel i", "Jamuna", "Somoy", "Ekattor",
    "NTV", "Bangla", "Boishakhi", "Desh", "Gazi", "DBC", "Mytv",
    "SA TV", "RTV", "Maasranga", "Shomoy", "Independent TV",
    "News24", "Channel 24", "Mohona", "Bijoy", "Bangladesh Television (BTV)",
"BTV World",
"BTv Chittagong",
"Bangladesh Parliament Television",
"BanglaVision",
"Channel i",
"NTV",
"RTV",
"Somoy TV",
"Jamuna TV",
"Ekattor TV",
"Independent TV",
"DBC News",
"News24",
"Channel 24",
"ATN Bangla",
"ATN News",
"Desh TV",
"Boishakhi TV",
"SA TV",
"Asian TV",
"Bijoy TV",
"My TV",
"Mohona TV",
"Duronto TV",
"Ananda TV",
"Gazi TV (GTV)",
"Masranga Television",
"Deepto TV",
"Nagorik TV",
"Bangla TV",
"Global TV",
"Republic Bangla",
"Channel S",
"Green TV",
"Ruposhi Bangla",
"Movie Bangla",
"Music Bangla",
"Bangla Plus",
"Bangla Vision UK",
"Channel 9",
"Channel 9 UK",
"Channel 16",
"Channel 21",
"Channel 23",
"Channel 26",
"Channel 39",
"Channel 52",
"Channel 57",
"Channel 71",
"Channel 77",
"Channel 81",
"Channel 86",
"Channel 88",
"Channel 90",
"Channel 91",
"Channel 92",
"Channel 93",
"Channel 94",
"Channel 95",
"Channel 96",
"Channel 97",
"Channel 98",
"Channel 99",
]

INDIA_KEYWORDS = [
    "Star Plus", "Star Jalsha", "Zee", "Sony", "Colors",
    "Sun TV", "Sony SAB", "DD National", "Sony Ten", "Aaj Tak",
    "Republic", "India TV", "Zee News", "NDTV", "TV9", "ABP",
    "Star Vijay", "Asianet", "Maa TV", "Gemini", "Star Plus","Star Bharat","Star Utsav","Colors TV","Colors HD","Colors Super","Colors Rishtey","Zee TV","Zee Anmol","Zee Anmol Cinema","&TV","Sony Entertainment Television","Sony SAB","Sony Pal","Dangal TV","Big Magic","DD National","DD Bharati","DD Kisan","DD News","DD Sports","Sansad TV","Aaj Tak","India TV","ABP News","News18 India","Republic Bharat","Zee News","News24","NDTV India","TV9 Bharatvarsh","Times Now Navbharat","News Nation","CNBC Awaaz","CNBC TV18","ET Now","Star Sports 1","Star Sports 1 Hindi","Star Sports 2","Star Sports 3","Star Sports Select 1","Star Sports Select 2","Star Sports First","Sports18","Sports18 1","Sports18 2","Sports18 Khel","Sony Sports Ten 1","Sony Sports Ten 2","Sony Sports Ten 3","Sony Sports Ten 4","Sony Sports Ten 5","Eurosport India","Zee Cinema","Zee Bollywood","Zee Action","Zee Classic","Zee Theatre","Zee Biskop","Zee Picchar","Star Gold","Star Gold 2","Star Gold Select","Star Gold Thrills","Star Gold Romance","Colors Cineplex","Colors Cineplex Superhits","Colors Cineplex Bollywood","Sony Max","Sony Max 2","Sony Wah","B4U Movies","B4U Kadak","UTV Movies","Movies Now","MNX","Romedy Now","9XM","9X Jalwa","Zing","MTV India","VH1 India","Music India","Cartoon Network India","Pogo","Discovery Kids","Nick India","Nick Jr India","Disney Channel India","Disney Junior India","Hungama TV","Super Hungama","Sony YAY","History TV18","Discovery Channel India","Animal Planet India","National Geographic India","Nat Geo Wild India","Travel XP","Food Food","Zee Zest","Sony BBC Earth","Aastha TV","Aastha Bhajan","Sanskar TV","Sadhna TV","Vedic TV","Sun TV","Sun TV HD","Sun Music","Sun News","KTV","Kalaignar TV","Jaya TV","Raj TV","Raj Digital Plus","Vijay TV","Star Vijay","Vijay Super","Adithya TV","Gemini TV","Gemini Movies","Gemini Music","Gemini Comedy","ETV Telugu","ETV Andhra Pradesh","ETV Telangana","Star Maa","Zee Telugu","Zee Telugu HD","Zee Tamil","Zee Tamil HD","Asianet","Asianet News","Asianet Movies","Asianet Plus","Surya TV","Surya Music","Flowers TV","Flowers Comedy","Zee Keralam","Manorama News","Mathrubhumi News","News18 Kerala","Colors Kannada","Zee Kannada","Zee Kannada HD","Star Suvarna","Udaya TV","Udaya Movies","Udaya Music","TV9 Kannada","Public TV","Suvarna News","News First Kannada","Power TV","Zee Marathi","Zee Marathi HD","Colors Marathi","Star Pravah","Zee Yuva","ABP Majha","News18 Lokmat","TV9 Marathi","Zee Bangla","Zee Bangla HD","Star Jalsha","Colors Bangla","Sun Bangla","ETV Bangla","ABP Ananda","News18 Bangla","Zee Punjabi","PTC Punjabi","Chardikla Time TV","DD Punjabi","DD Odia","Zee Sarthak","Tarang TV","Kanak News","OTV","News18 Odisha","Kalinga TV","Prameya News7","TV5 News","TV9 Telugu","V6 News","N TV","10TV","Sakshi TV","ABN Andhra Jyothi","Studio N","News18 Rajasthan","News18 UP UK","News18 MP CG","News18 Bihar Jharkhand","News18 Punjab Haryana Himachal","Zee Rajasthan","Zee Uttar Pradesh Uttarakhand","Zee Madhya Pradesh Chhattisgarh","Zee Bihar Jharkhand","DD Tamil","DD Telugu","DD Kannada","DD Malayalam","DD Marathi","DD Gujarati","DD Odia","DD Urdu","DD Kashir","DD Arunprabha","DD North East",
]

CARTOON_KEYWORDS = [
    "Cartoon Network", "Nick", "Nickelodeon", "Disney",
    "Pogo", "Hungama", "BabyTV", "Toon", "CBeebies", "Baby", "Kids", "Cartoon Network",
"Cartoon Network HD",
"Cartoon Network USA",
"Cartoon Network UK",
"Cartoon Network Africa",
"Cartoon Network Arabia",
"Cartoon Network MENA",
"Cartoon Network India",
"Cartoon Network Pakistan",
"Cartoon Network Japan",
"Cartoon Network Korea",
"Cartoon Network Latin America",
"Cartoon Network Brazil",
"Cartoon Network Australia",
"Cartoon Network Southeast Asia",
"Boomerang",
"Boomerang HD",
"Boomerang USA",
"Boomerang UK",
"Boomerang Africa",
"Boomerang Arabia",
"Boomerang MENA",
"Boomerang Asia",
"Boomerang Latin America",
"Boomerang Brazil",
"Cartoonito",
"Cartoonito HD",
"Cartoonito UK",
"Cartoonito USA",
"Cartoonito Africa",
"Cartoonito MENA",
"Toonami",
"Toonami Asia",
"Toonami France",
"Toonami Africa",
"Tooncast",
"Tooncast HD",
"Disney Channel",
"Disney Channel HD",
"Disney Junior",
"Disney Junior HD",
"Disney XD",
"Disney XD HD",
"Disney Channel USA",
"Disney Channel UK",
"Disney Channel Africa",
"Disney Channel Asia",
"Disney Channel Japan",
"Disney Channel Korea",
"Disney Channel Latin America",
"Nickelodeon",
"Nickelodeon HD",
"Nick Jr",
"Nick Jr HD",
"Nicktoons",
"Nicktoons HD",
"TeenNick",
"TeenNick HD",
"NickMusic",
"NickMusic HD",
"Nickelodeon USA",
"Nickelodeon UK",
"Nickelodeon Africa",
"Nickelodeon Arabia",
"Nickelodeon Asia",
"Nickelodeon India",
"Nickelodeon Pakistan",
"Nickelodeon Germany",
"Nickelodeon Australia",
"Nickelodeon Latin America",
"PBS Kids",
"PBS Kids HD",
"Universal Kids",
"Universal Kids HD",
"CBeebies",
"CBeebies HD",
"CBBC",
"CBBC HD",
"Pop",
"Pop HD",
"Pop Max",
"Pop Max HD",
"Tiny Pop",
"Tiny Pop HD",
"YTV",
"YTV HD",
"Teletoon",
"Teletoon HD",
"Treehouse TV",
"Treehouse TV HD",
"Family Channel",
"Family Jr",
"Family CHRGD",
"KIKA",
"KIKA HD",
"Super RTL",
"TOGGO",
"RTL Super",
"Boing",
"Boing HD",
"Canal Panda",
"Clan TVE",
"Rai Yoyo",
"Rai Gulp",
"JimJam",
"JimJam HD",
"BabyTV",
"BabyTV HD",
"BabyFirst",
"BabyFirst HD",
"ZooMoo",
"ZooMoo HD",
"Da Vinci Kids",
"Da Vinci Kids HD",
"Knowledge Kids",
"Moonbug Kids",
"Moonbug Kids HD", "Spacetoon",
"Spacetoon HD",
"Spacetoon English",
"Spacetoon Arabic",
"Majid Kids",
"Majid Kids HD",
"Ajyal TV",
"Alwan TV",
"Cartoon Network Arabic",
"Cartoon Network MENA",
"Nickelodeon Arabia",
"Disney Channel Arabia",
"Disney Junior Arabia",
"BabyTV Arabia",
"CN Arabic",
"MBC3",
"MBC3 HD",
"Jeem TV",
"Jeem HD",
" Baraem",
"Baraem HD",
"Qatar Kids",
"Sharjah TV Kids",
"Al Rayyan Kids",

"Super Hungama",
"Sony YAY",
"Nick India",
"Nick HD+",
"Nick Jr India",
"Hungama TV",
"Discovery Kids India",
"Pogo",
"Pogo HD",
"Cartoon Network India",
"Disney Channel India",
"Disney Junior India",
"Disney XD India",
"Marvel HQ",
"Marvel HQ HD",

"Animax",
"Animax HD",
"Animax Asia",
"Aniplus",
"Aniplus HD",
"Kids Station",
"Kids Station HD",
"NHK E Tele",
"NHK Kids",
"Disney Channel Japan",
"Disney Junior Japan",
"Cartoon Network Japan",
"Tooniverse",
"Tooniverse HD",
"Champ TV",
"Champ TV HD",
"Anione",
"Anibox",
"Kids TV Japan",
"TV Tokyo Kids",
"BS11 Kids",

"Cartoon Network Korea",
"Disney Channel Korea",
"Disney Junior Korea",
"Tooniverse Korea",
"Champ Korea",
"Anione Korea",

"Disney Channel Southeast Asia",
"Disney Junior Southeast Asia",
"Nickelodeon Southeast Asia",
"Cartoon Network Southeast Asia",
"Boomerang Southeast Asia",
"DreamWorks Channel",
"DreamWorks Channel HD",
"DreamWorks Asia",
"DreamWorks Kids",
"DreamWorks Animation",

"Kids Central",
"Okto",
"ZooMoo Asia",
"Da Vinci Kids Asia",
"BabyTV Asia",
"BabyFirst Asia",

"ABC Kids",
"ABC ME",
"ABC ME HD",
"Disney Channel Australia",
"Disney Junior Australia",
"Cartoon Network Australia",
"Boomerang Australia",
"Nickelodeon Australia",
"Nick Jr Australia", "Cartoon Network France",
"Cartoon Network Spain",
"Cartoon Network Italy",
"Cartoon Network Germany",
"Cartoon Network Netherlands",
"Cartoon Network Poland",
"Cartoon Network Portugal",
"Cartoon Network Nordic",
"Cartoon Network Turkey",

"Boomerang France",
"Boomerang Spain",
"Boomerang Italy",
"Boomerang Germany",
"Boomerang Netherlands",
"Boomerang Poland",
"Boomerang Portugal",
"Boomerang Nordic",

"Disney Channel France",
"Disney Channel Spain",
"Disney Channel Italy",
"Disney Channel Germany",
"Disney Channel Netherlands",
"Disney Channel Poland",
"Disney Channel Portugal",
"Disney Channel Nordic",

"Disney Junior France",
"Disney Junior Spain",
"Disney Junior Italy",
"Disney Junior Germany",

"Nickelodeon France",
"Nickelodeon Spain",
"Nickelodeon Italy",
"Nickelodeon Germany",
"Nickelodeon Netherlands",
"Nickelodeon Poland",
"Nickelodeon Portugal",

"Nick Jr France",
"Nick Jr Spain",
"Nick Jr Italy",
"Nick Jr Germany",

"Nicktoons UK",
"Nicktoons France",
"Nicktoons Spain",

"Super RTL",
"TOGGO Plus",
"KIKA",
"KIKA HD",
"RiC TV",
"Fix & Foxi",
"Fix & Foxi HD",

"Boing Spain",
"Boing France",
"Boing Italy",
"Boing Africa",

"Canal Panda",
"Canal Panda Portugal",
"Panda Kids",

"Clan TVE",
"Rai Yoyo",
"Rai Gulp",
"Frisbee",
"DeAKids",
"DeA Junior",

"Canal J",
"Gulli",
"Gulli Max",
"TiJi",
"Piwi+",

"Cartoon Network Latin America",
"Cartoon Network Brazil",
"Cartoon Network Mexico",
"Cartoon Network Chile",
"Cartoon Network Argentina",

"Boomerang Latin America",
"Boomerang Brazil",

"Disney Channel Latin America",
"Disney Junior Latin America",
"Disney XD Latin America",

"Nickelodeon Latin America",
"Nick Jr Latin America",

"Discovery Kids Latin America",
"Discovery Kids Brazil",
"Discovery Kids Mexico",

"Gloob",
"Gloobinho",
"TV Rá-Tim-Bum",
"ZooMoo Brazil",

"Cartoon Network Africa",
"Boomerang Africa",
"Disney Channel Africa",
"Disney Junior Africa",
"Nickelodeon Africa",
"Nick Jr Africa",
"Nicktoons Africa",

"JimJam Africa",
"BabyTV Africa",
"BabyFirst Africa",
"Da Vinci Kids Africa",
"Mindset Kids",
"Akili Kids",

"eToonz",
"Smile TV",
"Smile of a Child",
"Yippee TV",
"Yippee Kids", "ABC Kids",
"ABC ME",
"ABC ME HD",
"Treehouse TV",
"Family Jr",
"Family CHRGD",
"YTV",
"YTV HD",
"Teletoon",
"Teletoon HD",
"Disney Channel Canada",
"Disney Junior Canada",
"Nickelodeon Canada",
"Nick Jr Canada",

"BabyTV",
"BabyTV HD",
"BabyTV Europe",
"BabyTV Middle East",
"BabyTV Asia",
"BabyFirst",
"BabyFirst HD",
"BabyFirst Europe",
"BabyFirst Asia",

"Smile TV",
"Smile HD",
"Smile of a Child",
"Smile of a Child HD",
"Yippee TV",
"Yippee HD",
"Sonlife Kids",
"God TV Kids",

"Moonbug Kids",
"Moonbug Kids HD",
"CoComelon TV",
"CoComelon Kids",
"Ryan & Friends",
"Ryan and Friends",

"Little Angel TV",
"Little Angel HD",
"Super Simple TV",
"KidsFlix",
"KidsFlix HD",
"Kidoodle TV",
"Kidoodle TV HD",

"ZooMoo",
"ZooMoo HD",
"ZooMoo Kids",
"Da Vinci Kids",
"Da Vinci Kids HD",
"Da Vinci Learning Kids",

"Knowledge Kids",
"Knowledge Kids HD",
"Curiosity Kids",
"Curiosity Stream Kids",

"Toon Goggles",
"Toon Goggles HD",
"Toon Goggles Kids",
"BatteryPop",
"BatteryPop Kids",

"Animax",
"Animax Asia",
"Animax HD",
"Aniplus",
"Aniplus HD",
"Anime Network",
"Anime Channel",

"KidsCo",
"KidsCo HD",
"JimJam",
"JimJam HD",
"JimJam Kids",

"Kids Central",
"Okto",
"Okto HD",

"Hop",
"Hop TV",
"Hop Channel",
"Jeem TV",
"Jeem HD",

"Cartoon Network Hindi",
"Cartoon Network Tamil",
"Cartoon Network Telugu",
"Cartoon Network Kannada",

"Nick Hindi",
"Nick Tamil",
"Nick Telugu",
"Nick Kannada",

"Disney Channel Hindi",
"Disney Channel Tamil",
"Disney Channel Telugu",

"Panda Kids",
"Panda Futura",
"Baby TV Turkey",
"Minika Çocuk",
"Minika GO",

"TRT Çocuk",
"TRT Kids",
"Yumurcak TV",

"Ketnet",
"Ketnet HD",
"Karusel",
"Karusel HD",
"Multimania",
"Multimania HD",

"Boomerang Nordic",
"Cartoon Network Nordic",
"Nickelodeon Nordic",

"Polsat JimJam",
"Teletoon+",
"MiniMini+",
"MiniMini+ HD",

"Cartoon Network Israel",
"Hop Israel",
"Junior TV",
"Logi TV",
]

NEWS_KEYWORDS = [
    "News", "Samachar", "Khobor", "BBC", "CNN", "Al Jazeera",
    "CNBC", "Bloomberg", "Sky News", "France 24", "DW", "Euronews",
]

SPORTS_KEYWORDS = [
    "Sport", "ESPN", "Star Sports", "Sony Six", "Ten Sports",
    "Willow", "DSport", "Cricket", "Football", "FIFA", "Sky Sports",
    "BT Sport", "Sony LIV Sports", "ESPN",
"ESPN HD",
"ESPN2",
"ESPN2 HD",
"ESPN Deportes",
"ESPN Caribbean",
"ESPN Africa",
"ESPN Asia",
"ESPN India",
"ESPN Brazil",

"FOX Sports",
"FOX Sports 1",
"FOX Sports 2",
"FOX Sports HD",
"FOX Deportes",
"FS1",
"FS2",

"Sky Sports Main Event",
"Sky Sports News",
"Sky Sports Premier League",
"Sky Sports Football",
"Sky Sports Cricket",
"Sky Sports F1",
"Sky Sports Golf",
"Sky Sports Tennis",
"Sky Sports Arena",
"Sky Sports Mix",

"beIN Sports",
"beIN Sports HD",
"beIN Sports 1",
"beIN Sports 2",
"beIN Sports 3",
"beIN Sports 4",
"beIN Sports 5",
"beIN Sports 6",
"beIN Sports 7",
"beIN Sports 8",
"beIN Sports 9",
"beIN Sports 10",
"beIN Sports Max",
"beIN Sports Max 1",
"beIN Sports Max 2",
"beIN Sports Max 3",
"beIN Sports Max 4",
"beIN Sports Max 5",
"beIN Sports Max 6",

"DAZN",
"DAZN 1",
"DAZN 2",
"DAZN F1",

"Eurosport",
"Eurosport 1",
"Eurosport 2",
"Eurosport HD",

"BT Sport",
"TNT Sports",
"TNT Sports 1",
"TNT Sports 2",
"TNT Sports 3",
"TNT Sports 4",
"TNT Sports 5",

"Premier Sports",
"Premier Sports 1",
"Premier Sports 2",

"SuperSport",
"SuperSport 1",
"SuperSport 2",
"SuperSport 3",
"SuperSport 4",
"SuperSport 5",
"SuperSport 6",
"SuperSport 7",
"SuperSport 8",
"SuperSport 9",
"SuperSport 10",

"Star Sports",
"Star Sports 1",
"Star Sports 1 Hindi",
"Star Sports 2",
"Star Sports 3",
"Star Sports Select 1",
"Star Sports Select 2",
"Star Sports First",

"Sports18",
"Sports18 1",
"Sports18 2",
"Sports18 Khel",

"Sony Sports Ten 1",
"Sony Sports Ten 2",
"Sony Sports Ten 3",
"Sony Sports Ten 4",
"Sony Sports Ten 5",

"Eurosport India",
"Willow TV",
"Willow HD",
"FanCode",
"JioSports",

"TSports",
"TSports HD",
"Toffee Sports",
"GTV Sports",

"RMC Sport",
"Canal+ Sport",
"Canal+ Foot",
"Canal+ Rugby",

"Viaplay Sports",
"Viaplay Xtra",

"Sport TV",
"Sport TV1",
"Sport TV2",
"Sport TV3",
"Sport TV4",
"Sport TV5", "Premier League TV",
"LFCTV",
"MU TV",
"Manchester United TV",
"City+",
"Real Madrid TV",
"Barca TV",
"Barca One",
"Inter TV",
"AC Milan TV",
"Juventus TV",

"Eleven Sports",
"Eleven Sports 1",
"Eleven Sports 2",
"Eleven Sports 3",
"Eleven Sports 4",
"Eleven Sports 5",

"Mola TV Sport",
"Astro SuperSport",
"Astro Arena",
"Astro Arena 2",
"Astro Cricket",
"beIN Sports Malaysia",

"True Sport",
"True Sport 1",
"True Sport 2",
"True Sport 3",
"True Sport 4",
"True Premier Football",
"True Premier Football 1",
"True Premier Football 2",

"SPOTV",
"SPOTV2",
"SPOTV NOW",

"J Sports",
"J Sports 1",
"J Sports 2",
"J Sports 3",
"J Sports 4",

"DAZN Japan",
"DAZN Korea",

"KBSN Sports",
"SBS Sports",
"MBC Sports+",

"Coupang Play Sports",

"CCTV Sports",
"CCTV5",
"CCTV5+",
"CCTV Olympic",

"iQIYI Sports",
"Tencent Sports",

"Dubai Sports",
"Dubai Sports 1",
"Dubai Sports 2",
"Dubai Racing",
"Abu Dhabi Sports",
"Abu Dhabi Sports 1",
"Abu Dhabi Sports 2",

"Oman Sports",
"Kuwait Sports",
"Saudi Sports",
"SSC Sports",
"SSC 1",
"SSC 2",
"SSC 3",
"SSC 4",
"Qatar Sports",

"Al Kass Sports",
"Al Kass 1",
"Al Kass 2",
"Al Kass 3",
"Al Kass 4",
"Al Kass 5",

"Ziggo Sport",
"Ziggo Sport Select",
"Ziggo Sport Racing",

"Polsat Sport",
"Polsat Sport Extra",
"Polsat Sport Fight",

"TVP Sport",
"TVP Sport HD",

"Nova Sport",
"Nova Sport 1",
"Nova Sport 2",

"Sport Klub",
"Sport Klub 1",
"Sport Klub 2",

"Arena Sport",
"Arena Sport 1",
"Arena Sport 2",
"Arena Sport 3",

"RTS Sport",
"Movistar Deportes",
"Movistar LaLiga",
"Movistar Liga de Campeones",

"TUDN",
"TUDN USA",
"Univision Deportes",
"Telemundo Deportes",
"Universo Deportes",

"Gol TV",
"GOL PLAY",

"TyC Sports",
"ESPN Argentina",
"Fox Sports Argentina",

"BandSports",
"Premiere Sports",
"Sportv",
"Sportv2",
"Sportv3",

"Claro Sports",
"Claro Sports HD",

"Win Sports",
"Win Sports+",

"Caracol Sports",
"RCN Deportes",

"Azteca Deportes",
"Canal 5 Deportes", "Willow Cricket",
"Willow Xtra",
"Willow HD",
"Sky Sports Cricket",
"SuperSport Cricket",
"BT Sport Cricket",
"Star Sports Cricket",
"Star Sports 1 Cricket",
"PTV Sports",
"A Sports",
"Ten Sports",
"Geo Super",
"Tapmad Sports",
"Prime Sports",
"Sports TV Cricket",

"Fox Cricket",
"Channel 7 Sport",
"Nine Sport",
"BT Sport Ultimate",

"ATP Tennis TV",
"WTA TV",
"Tennis Channel",
"Tennis Channel HD",
"Eurosport Tennis",
"Sky Sports Tennis",

"Golf Channel",
"Golf Channel HD",
"Sky Sports Golf",
"Eurosport Golf",

"Formula 1 TV",
"F1 TV",
"Sky Sports F1",
"Motorsport TV",
"Motorvision TV",
"Auto Motor Sport",
"Speedvision",

"NBA TV",
"NBA TV HD",
"NFL Network",
"NFL RedZone",
"MLB Network",
"NHL Network",
"Fight Network",
"UFC Fight Pass",
"UFC TV",

"WWE Network",
"WWE Channel",
"AEW Plus",

"BoxNation",
"DAZN Boxing",
"Premier Boxing Champions",

"Extreme Sports",
"Extreme Sports Channel",
"Fuel TV",
"Red Bull TV",
"Red Bull Racing",

"Surf Channel",
"World Surf League TV",
"Fishing TV",
"Horse TV",
"Racing TV",
"At The Races",

"Dubai Racing",
"Racing TV HD",
"Equidia",

"Chess TV",
"PokerGO",
"Poker TV",

"Motors TV",
"Bike Channel",
"Bike TV",

"Outdoor Channel",
"Outdoor Channel HD",
"Hunting Channel",
"Fishing Channel",

"Adventure Sports TV",
"Adventure Sports Network",
"World Chase Tag TV",

"Olympic Channel",
"Olympic Channel HD",
"World Athletics Channel",

"FIBA TV",
"Volleyball World TV",
"World Rugby TV",
"Handball TV",

"Formula E TV",
"FIA WEC TV", "TSN",
"TSN1",
"TSN2",
"TSN3",
"TSN4",
"TSN5",
"Sportsnet",
"Sportsnet One",
"Sportsnet World",
"RDS Sport",

"NBC Sports",
"NBC Sports Network",
"NBC Sports Bay Area",
"NBC Sports Boston",
"NBC Sports California",
"NBC Sports Chicago",
"NBC Sports Philadelphia",
"NBC Sports Washington",

"YES Network",
"MSG Network",
"NESN",
"Altitude Sports",
"Marquee Sports Network",

"SEC Network",
"ACC Network",
"Big Ten Network",
"Pac-12 Network",

"Fox Sports Regional",
"FanDuel Sports Network",

"beIN Sports USA",
"Golazo Network",

"ESPN UK",
"ESPN Australia",
"ESPN New Zealand",

"Fox Sports Australia",
"Kayo Sports",
"Stan Sport",

"Optus Sport",
"Sky Sport NZ",
"Sky Sport 1 NZ",
"Sky Sport 2 NZ",
"Sky Sport 3 NZ",

"SuperSport Blitz",
"SuperSport Variety 1",
"SuperSport Variety 2",
"SuperSport Variety 3",
"SuperSport Variety 4",

"Zee Sports",
"Zee Sports HD",
"DD Sports HD",

"Eurosport Romania",
"Eurosport Poland",
"Eurosport France",
"Eurosport Germany",

"Sport1",
"Sport1 HD",
"Sportdigital",
"Sportdigital HD",

"DAZN 1 Germany",
"DAZN 2 Germany",

"Eleven Sports Poland",
"Eleven Sports Belgium",

"Canal+ Sport France",
"Canal+ Sport 360",

"RTÉ Sport",
"TG4 Sport",

"NOS Sport",
"ESPN Netherlands",

"V Sport",
"V Sport Football",
"V Sport Hockey",

"Match TV",
"Match TV HD",
"Match Premier",

"Okko Sport",

"Setanta Sports",
"Setanta Sports Eurasia",

"VTV Cabal Sport",
"VTV Sports",

"Sport TV Portugal",

"BandSports HD",
"Premiere Futebol",

"Fox Sports Mexico",
"TUDN Mexico",
"ESPN Mexico",

"ESPN Brasil",
"ESPN Extra",

"TyC Sports Internacional",

"DirecTV Sports",
"D Sports",
"D Sports Fight",
"D Sports Motor",

"Caribbean Sports Network",
"SportsMax",
"SportsMax 2",

"Flow Sports",

"Star Sports Tamil",
"Star Sports Telugu",
"Star Sports Kannada",
"Star Sports Marathi",

"Eurosport 4K",
"Sky Sports 4K",
"beIN Sports 4K",
]

MOVIES_KEYWORDS = [
    "Movies", "Cinema", "Film", "Zee Cinema", "Star Gold",
    "Sony Max", "B4U", "Action", "Thriller", "Romedy", "&Pictures", "Star Movies",
"Star Movies HD",
"Star Movies Select",
"Star Movies Select HD",
"Zee Cinema",
"Zee Cinema HD",
"Zee Bollywood",
"Zee Bollywood HD",
"Zee Action",
"Zee Classic",
"Zee Anmol Cinema",
"Sony Max",
"Sony Max HD",
"Sony Max 2",
"Sony Wah",
"Colors Cineplex",
"Colors Cineplex HD",
"Colors Cineplex Bollywood",
"Colors Cineplex Superhits",
"Movies Now",
"Movies Now HD",
"MNX",
"MNX HD",
"Romedy Now",
"Romedy Now HD",
"B4U Movies",
"B4U Kadak",
"UTV Movies",
"UTV Action",
"Zee Studio",
"Zee Studio HD",

"HBO",
"HBO HD",
"HBO 2",
"HBO Comedy",
"HBO Family",
"HBO Signature",
"HBO Hits",
"HBO Zone",
"Cinemax",
"Cinemax HD",

"AMC",
"AMC HD",
"FXM",
"FXM HD",
"FXX",
"FXX HD",
"Showtime",
"Showtime HD",
"Showtime 2",
"Showtime Extreme",
"Starz",
"Starz HD",
"Starz Cinema",
"Starz Encore",
"Encore",

"Paramount Network",
"Paramount Network HD",
"Comedy Central",
"Comedy Central HD",
"MTV Movies",

"Film4",
"Film4 HD",
"Great! Movies",
"Great! Movies Classic",
"Talking Pictures TV",

"Canal+ Cinema",
"Canal+ Cinema HD",
"Canal+ Family",
"Canal+ Action",
"Canal+ Premier",

"Sky Cinema",
"Sky Cinema HD",
"Sky Cinema Premiere",
"Sky Cinema Action",
"Sky Cinema Comedy",
"Sky Cinema Family",
"Sky Cinema Thriller",

"Netflix Movies",
"Prime Movies",
"Rakuten TV Movies",

"Fox Movies",
"Fox Movies HD",
"Fox Action Movies",
"Fox Family Movies",

"True Film",
"True Film HD",
"True Movie",

"Cinema One",
"Cinema World",
"Cinema Asia",

"Movie Channel",
"The Movie Channel",
"Movie Channel HD", "Colors Cineplex Tamil",
"Colors Cineplex Telugu",
"Colors Cineplex Kannada",
"Zee Cinemalu",
"Zee Thirai",
"Zee Flix",
"Zee Theatre",
"Star Gold",
"Star Gold HD",
"Star Gold 2",
"Star Gold Select",
"Star Gold Romance",
"Star Gold Thrills",
"Sony Max",
"Sony Max HD",
"Sony Max 2",
"Manoranjan Movies",
"Manoranjan Grand",
"Enterr10 Movies",
"Enterr10 Bangla",
"Rishtey Cineplex",
"Goldmines",
"Goldmines HD",
"Goldmines Bollywood",
"Goldmines Movies",
"B4U Movies",
"B4U Movies HD",
"B4U Kadak",
"Dhinchaak",
"Movie Plus",
"Wow Cinema",

"Sun TV Movies",
"KTV",
"KTV HD",
"Sun Life",
"Kalaignar Movies",
"Raj Digital Plus",
"Raj Movies",
"Jaya Max",
"Adithya TV",

"Gemini Movies",
"Gemini Movies HD",
"Udaya Movies",
"Udaya Movies HD",
"Surya Movies",
"Asianet Movies",
"Zee Keralam Movies",

"Zee Marathi Movies",
"Zee Bangla Cinema",
"Zee Punjabi Cinema",

"UTV Movies",
"UTV Action",
"Movies OK",

"Star Movies Tamil",
"Star Movies Telugu",

"Asianet Movies",
"Asianet Movies HD",

"Fox Movies Asia",
"Fox Family Movies Asia",
"Fox Action Movies Asia",

"Celestial Movies",
"Celestial Movies HD",
"Celestial Classic Movies",

"Thrill",
"Thrill HD",
"Hits Movies",
"Hits Movies HD",

"CinemaWorld",
"CinemaWorld HD",
"Hits",
"Hits HD",

"BeTV Movies",
"DreamWorks",
"DreamWorks HD",
"DreamWorks Animation",

"OSN Movies",
"OSN Movies HD",
"OSN Movies Action",
"OSN Movies Comedy",
"OSN Movies Family",
"OSN Movies Premiere",

"MBC Bollywood",
"MBC Bollywood HD",
"MBC2",
"MBC2 HD",
"MBC Max",
"MBC Max HD",
"MBC Action",
"MBC Action HD",

"Rotana Cinema",
"Rotana Cinema HD",
"Rotana Classic",
"Rotana Drama",

"Dubai One",
"Dubai One HD",
"Abu Dhabi Movies",
"Al Aan Movies",
"TNT",
"TNT HD",
"TBS",
"TBS HD",
"TCM",
"TCM HD",
"AMC",
"AMC HD",
"FXM",
"FXM HD",
"FXX",
"FXX HD",
"Syfy",
"Syfy HD",
"Universal TV",
"Universal Channel",
"Universal Movies",

"Hallmark Movies & Mysteries",
"Hallmark Channel",
"Hallmark Drama",
"Lifetime Movies",
"Lifetime Movie Network",
"LMN HD",

"Freeform",
"Freeform HD",
"ABC Family",

"Bounce TV",
"Bounce XL",
"ION Television",
"ION Mystery",
"ION Plus",

"TruTV",
"TruTV HD",
"Vice TV",
"Vice TV HD",

"Pop TV",
"Pop TV HD",
"WE tv",
"WE tv HD",

"Showcase",
"Showcase Action",
"Showcase Classics",

"Sky Cinema Premiere",
"Sky Cinema Hits",
"Sky Cinema Action",
"Sky Cinema Comedy",
"Sky Cinema Drama",
"Sky Cinema Family",
"Sky Cinema Greats",

"Film4",
"Film4 HD",
"Film4+1",
"Movies4Men",
"Talking Pictures TV",

"Canal+ Cinema",
"Canal+ Cinema HD",
"Canal+ Family",
"Canal+ Action",
"Canal+ Box Office",

"OCS Max",
"OCS City",
"OCS Choc",

"RTL Crime",
"RTL Passion",
"RTL Living",

"ProSieben FUN",
"Kabel Eins Classics",
"Sat.1 Emotions",

"Tele5",
"Kinowelt TV",
"Warner TV Film",
"Warner TV Comedy",

"Paramount Network France",
"Paramount Network Spain",
"Paramount Network Italy",

"Fox Movies Latin America",
"Fox Action Movies Latin America",
"Fox Family Movies",

"Space",
"Space HD",
"Studio Universal",
"Studio Universal HD",

"Universal Cinema",
"Golden Premier",
"Golden Edge",

"Cinemax Latin America",
"HBO Latin America",
"HBO Family Latin America",
"HBO Plus",
"HBO Signature",

"Moviecity",
"Moviecity Action",
"Moviecity Family",

"Cinecanal",
"Cinecanal HD",
"Cinemax",
"The Film Zone", "NHK BS Premium",
"NHK BS Cinema",
"WOWOW Cinema",
"WOWOW Prime",
"WOWOW Live",

"Star Chinese Movies",
"Star Chinese Movies HD",
"Celestial Movies",
"Celestial Classic Movies",
"Phoenix Movies",
"Phoenix Movie Channel",

"China Movie Channel",
"CCTV Movie",
"CCTV6",

"TVB Movies",
"TVB Jade Movies",
"TVB Pearl",

"ViuTVsix",

"One TV",
"One Movies",
"J Movie",

"K Movie Channel",
"KMOVIE",

"True Film",
"True Film HD",
"True Movie HD",

"Mono29",
"Mono Max",

"Channel Film HD",
"Zee Film",

"Gemini Movies",
"Gemini Movies HD",
"ETV Cinema",

"Sun Life",
"KTV Movies",

"Udaya Movies",
"Udaya Movies HD",

"Raj Movies",
"Raj Digital Plus",

"Jaya Max",
"Kalaignar Movies",

"Asianet Movies",
"Asianet Movies HD",

"Surya Movies",

"Zee Anmol Cinema",
"Zee Flix",
"Zee Theatre",

"Star Utsav Movies",

"Romedy Now",
"Romedy Now HD",

"Movie Plus",
"Movie Plus HD",

"Cinema One",
"Cinema World",
"Cinema World HD",

"Hits Movies",
"Hits Movies HD",

"Thrill",
"Thrill HD",

"Movies Central",
"Movies Central HD",

"Star Chinese Movies Legend",

"OSN Movies Premiere",
"OSN Movies First",
"OSN Movies Action",
"OSN Movies Comedy",
"OSN Movies Kids",

"Rotana Cinema",
"Rotana Classic",
"Rotana Aflam",

"Al Kass Movies",
"Saudi Cinema",
"Dubai Zaman",

"AMC Middle East",
"FOX Movies Middle East",

"FilmBox",
"FilmBox Plus",
"FilmBox Action",
"FilmBox Family",
"FilmBox Arthouse",

"Bollywood HD",
"Bollywood Classic",
"Bollywood Hits",

"Cinema TV",
"Cinema TV HD",

"Action Max",
"Action Max HD",

"Drama Max",
"Drama Max HD",

"Family Max",
"Family Max HD", 
]

MUSIC_KEYWORDS = [
    "Music", "MTV", "VH1", "Channel V", "Zing", "9X Jalwa",
    "Hits", "Beats", "Radio", "MTV",
"MTV HD",
"MTV Hits",
"MTV Classic",
"MTV Live",
"MTV 00s",
"MTV 80s",
"MTV 90s",
"MTV Music",
"MTV Base",

"VH1",
"VH1 HD",
"VH1 Classic",

"4Music",
"4Music HD",
"The Box",
"Kerrang!",
"Kiss TV",
"Kiss TV HD",

"Vevo TV",
"Vevo Pop",
"Vevo Hip Hop",
"Vevo Country",

"Trace Urban",
"Trace Latina",
"Trace Caribbean",
"Trace Africa",
"Trace Gospel",

"iConcerts",
"iConcerts HD",
"Qello Concerts",

"Stingray Music",
"Stingray Hits",
"Stingray Retro",
"Stingray Karaoke",

"Music Choice",
"Music Choice Hits",
"Music Choice Pop",
"Music Choice Rock",
"Music Choice Country",

"NOW 70s",
"NOW 80s",
"NOW 90s",
"NOW 00s",

"Clubland TV",
"Clubland TV HD",
"Chart Show TV",

"Heart TV",
"Magic TV",
"Magic Soul",
"Kiss",
"Box Hits",

"Channel U",
"Channel AKA",

"Mezzo",
"Mezzo Live HD",
"Mezzo HD",

"Classica",
"Classica HD",

"MTV Germany",
"MTV UK",
"MTV Europe",
"MTV France",
"MTV Italy",
"MTV Spain",
"MTV Africa",
"MTV Asia",

"NickMusic",
"NickMusic HD",

"Music India",
"9XM",
"9X Jalwa",
"Zing",
"Zoom",
"ETC Bollywood",
"B4U Music", "Zee Music Company",
"Zee Music HD",
"Zee ETC",
"Zee ETC Bollywood",
"MTV India",
"MTV Beats",
"MTV Beats HD",
"VH1 India",
"9XM",
"9X Jalwa",
"Zing",
"Zoom TV",
"B4U Music",
"B4U Music HD",
"Music India",
"Showbox",
"Showbox HD",
"Channel V",
"Channel V India",
"Bindass",
"DD National Music",

"Sun Music",
"Sun Music HD",
"Sun News Music",
"KTV Music",
"Isaiaruvi",
"Jaya Max",
"Raj Musix",
"Raj Musix HD",

"Gemini Music",
"Gemini Music HD",
"ETV Plus Music",
"ETV Telugu Music",

"Udaya Music",
"Udaya Music HD",
"Surya Music",
"Surya Music HD",

"Asianet Music",
"Zee Bangla Music",

"PTC Punjabi Music",
"PTC Chakde",
"MH1",
"MH1 Music",

"Channel Punjabi",
"Punjabi Hits",

"Colors Bangla Music",

"Anjan TV",
"Anjan TV Music",

"Star Vijay Music",

"Music Box",
"Music Box HD",

"MTV China",
"MTV Asia",
"MTV Japan",
"MTV Korea",

"Channel [V] International",
"Channel [V] Asia",

"Yin Yue Tai",
"QQ Music TV",

"JOOX TV",

"Arirang",
"Arirang HD",
"K-Pop TV",
"Mnet",
"Mnet HD",
"1theK",

"Music On! TV",
"Space Shower TV",
"MTV Japan",

"Arabic Music",
"Rotana Music",
"Rotana Music HD",
"Rotana Clips",
"Nogoum FM TV",
"Mazzika",
"Mazzika HD",
"Melody Hits",
"Melody Aflam Music",

"Trace Urban",
"Trace MENA",
"Trace Arabia",
"Trace Africa",

"Afro Music",
"Afro Music HD",
"Channel O",
"Sound City",
"Sound City HD", "Music Box",
"Music Box HD",
"Music Box Russia",
"Music Box UA",

"RFM TV",
"NRJ Hits",
"NRJ Hits HD",
"Trace Urban",
"Trace Latina",
"Trace Tropical",
"Trace Vault",
"Clubbing TV",
"Clubbing TV HD",

"Deluxe Music",
"Deluxe Music HD",
"DMAX Music",
"Folx TV",
"Folx Music",
"Folx Music Television",

"Viva",
"Viva HD",
"Viva Germany",
"Viva Poland",

"Hit TV",
"Hit TV HD",
"Hit Radio TV",
"Schlager Deluxe",

"Channel One Russia Music",
"RU.TV",
"RU.TV HD",
"Muz TV",
"Muz TV HD",
"Music Box Russia",

"Europa Plus TV",
"Europa Plus HD",

"Bridge TV",
"Bridge TV HD",
"Bridge Hits",
"Bridge Classic",

"MTV Europe",
"MTV Hits Europe",
"MTV Rocks",
"MTV Club",
"MTV Dance",

"VH1 Europe",
"VH1 Classic Europe",

"Latino Music",
"Latino Music HD",
"HTV",
"HTV HD",

"Telehit",
"Telehit HD",
"Telehit Plus",
"BandaMax",
"Ritmoson",

"MTV Latin America",
"MTV Hits Latin",
"VH1 Latin",

"Canal Fiesta",
"HTV Latino",

"Music Top",
"Music Top HD",

"Afrobeats TV",
"Afro Music",
"Afro Music HD",
"Channel O",
"Channel O HD",
"Sound City",
"Sound City HD",
"Trace Africa",
"Trace Gospel",
"Trace Naija",

"Gospel Music Channel",
"Hope Channel Music",

"Country Music TV",
"CMT",
"CMT HD",

"Country Network",

"Classic Arts Showcase",
"Mezzo",
"Mezzo Live HD",
"Stingray Classica",

"Qello Concerts",
"iConcerts",
"Concert Channel",

"Live Concert Channel",
"Live Music TV",

"Karaoke TV",
"Karaoke Channel",
"Stingray Karaoke",

"Clubland TV",
"Clubland TV HD",
"Dance Nation TV",
"Now Dance",

"Now 70s",
"Now 80s",
"Now 90s",
"Now 00s",

"Retro Music TV",
"Retro Music TV HD",

"Vintage TV",
"Vintage TV HD",

"VH1 Africa",
"MTV Africa",
"MTV Base Africa",
]

# Category display names & priority order
CATEGORY_ORDER = ["FIFA", "bd", "india", "cartoon", "news", "sports", "movies", "music", "other"]

CATEGORY_LABELS = {
    "FIFA":    "FWC 2026",
    "bd":      "Bangladesh",
    "india":   "India",
    "cartoon": "Kids & Cartoon",
    "news":    "News",
    "sports":  "Sports",
    "movies":  "Movies",
    "music":   "Music",
    "other":   "Other",
}

# ── Performance tuning ────────────────────────────────────────────────────────
MAX_WORKERS    = 200    # parallel threads for downloading & checking URLs
SOURCE_TIMEOUT = 20    # seconds to wait when fetching a source playlist
CHECK_TIMEOUT  = 8     # seconds per URL reachability check

# True  → skip per-URL check (fast, finishes in minutes, keeps dead links)
# False → HTTP HEAD/GET check each URL (filters dead links, recommended)
SKIP_URL_CHECK = False

# How many retries on connection error before marking a URL dead
CHECK_RETRIES = 1
